url: https://dolfelt.github.io/markdeck
baseurl: /markdeck
title: Markdeck
subTitle: Markdown Presentation Writer
favicon: https://raw.githubusercontent.com/dolfelt/markdeck/master/app/app.png
faviconType: image/png
repository: https://github.com/dolfelt/markdeck/

build:
  version: 0.1.0
  url:
    windows:
      x86: https://github.com/dolfelt/markdeck/releases/download/0.1.0/0.1.0-Markdeck-win32-ia32.zip
      x64: https://github.com/dolfelt/markdeck/releases/download/0.1.0/0.1.0-Markdeck-win32-x64.zip
    macosx:
      x64: https://github.com/dolfelt/markdeck/releases/download/0.1.0/0.1.0-Markdeck-mac.zip
    linux:
      x86: https://github.com/dolfelt/markdeck/releases/download/0.1.0/0.1.0-Markdeck-linux-ia32.tar.gz
      x64: https://github.com/dolfelt/markdeck/releases/download/0.1.0/0.1.0-Markdeck-linux-x64.tar.gz

exclude:
  - release/
  - dist/
  - node_modules/
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
