url: https://dolfelt.github.io/markdeck
baseurl: /markdeck
title: Markdeck
subTitle: Markdown Presentation Writer
favicon: https://raw.githubusercontent.com/dolfelt/markdeck/master/app/app.png
faviconType: image/png
repository: https://github.com/dolfelt/markdeck/

build:
  version: 0.0.2
  url:
    windows:
      x86: https://github.com/dolfelt/markdeck/releases/download/v0.0.2/0.0.2-Markdeck-win32-ia32.zip
      x64: https://github.com/dolfelt/markdeck/releases/download/v0.0.2/0.0.2-Markdeck-win32-x64.zip
    macosx:
      x64: https://github.com/dolfelt/markdeck/releases/download/v0.0.2/0.0.2-Markdeck-darwin-x64.dmg
    linux:
      x86: https://github.com/dolfelt/markdeck/releases/download/v0.0.2/0.0.2-Markdeck-linux-ia32.tar.gz
      x64: https://github.com/dolfelt/markdeck/releases/download/v0.0.2/0.0.2-Markdeck-linux-x64.tar.gz

exclude:
  - node_modules/
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
